### ISSUE TITLE
[FEATURE] - APR-V3 roadmap definition

### ISSUE THREAD

**Issue by Neogeekmo** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#104]
### Current Features
- Core
  - Route path definition (for speedrun and first character - route prefab) 
  - Player data ( Name, Realm, Faction, Level, Class, continent)
  - AFK
    - Timer
    - Frame 
  - Skip scene
  - Arrow
    - Direction
    - Coord calcul
    - Frame 
  - Custom path
    - Frame
    - path logic 
  - CheckPosMove
  - RoutePlanCheckPos (Check current position for route plan)
  - Event
    - ADDON_LOADED
    - CINEMATIC_START

- Command

- OptionPanel (move to wow addon setting page)
  - Setting Frame
  - Reset   

- Route
  - Route faction definition (Currently zone) 
  - Route files

- QuestHandler (route guide logic) 
  - ChkBreadcrums
  - APR_SendGroup
  - APR_LeaveQuest
  - APR_ExitVhicle
  - APR_QAskPopWanted
  - QAskPopWantedAsk
  - APR_PrintQStep
  - TrimPlayerServer
  - SetButton
  - CheckCRangeText
  - APR_UpdateQuest
  - MacroFinder
  - CreateMacro
  - MacroUpdater
  - MacroUpdater2
  - GliderFunc
  - APR_QuestStepIds
  - APR_RemoveQuest
  - APR_AddQuest
  - APR_UpdateMapId
  - APR_CheckZonePick
  - APR_AcceptQuester
  - APR_CheckDistance
  - APR_SetQPTT
  - APR_PosTest
  - APR_LoopBookingFunc
  - APR_BuyMerchFunc
  - APR_PopupFunc
  - APR_BookQStep
  - APR_UpdMapIDz
  - APR_UpdQuestThing
  - APR_UpdatezeMapId
  - APR_ZoneResetQnumb
  - GroupListingFunc
  - RepaintGroups
  - CheckSweatBuffz
  - Event
    - QUEST_REMOVED
    - QUEST_ACCEPTED
    - UNIT_QUEST_LOG_CHANGED
    - ZONE_CHANGED
    - ZONE_CHANGED_NEW_AREA
    - UPDATE_MOUSEOVER_UNIT
    - GOSSIP_SHOW
    - GOSSIP_CLOSED
    - UI_INFO_MESSAGE
    - HEARTHSTONE_BOUND
    - UNIT_SPELLCAST_SUCCEEDED
    - UNIT_SPELLCAST_START
    - QUEST_PROGRESS
    - QUEST_DETAIL
    - QUEST_COMPLETE
    - QUEST_FINISHED
    - TAXIMAP_OPENED
    - MERCHANT_SHOW
    - QUEST_GREETING
    - ITEM_PUSH
    - QUEST_AUTOCOMPLETE
    - QUEST_ACCEPT_CONFIRM
    - UNIT_ENTERED_VEHICLE
    - QUEST_LOG_UPDATE
    - PLAYER_TARGET_CHANGED
    - PLAYER_REGEN_ENABLED
    - PLAYER_REGEN_DISABLED
    - CHAT_MSG_ADDON
    - CHAT_MSG_MONSTER_SAY
    - CHAT_MSG_COMBAT_XP_GAIN
    - LEARNED_SPELL_IN_TAB
    - UNIT_AURA
    - PLAYER_CHOICE_UPDATE
    - REQUEST_CEMETERY_LIST_RESPONSE
    - AJ_REFRESH_DISPLAY
    - UPDATE_UI_WIDGET

- QuestList (Current Step list) 
  - Current Step frame
  - Event
    - ADDON_LOADED

- QuestTest (Route Quest List)
  -  GetPlayerMapPos
  - ZoneQuestOrderList
  - AddQuestOrderFrame
  - AddQuestIdFrame
  - AddQuestNameFrame
  - UpdateZoneQuestOrderList
  - MakeMapOrderIcons
  - MapOrderNumbers
  - Event
    - QUEST_LOG_UPDATE
- Transport
  - TestDest
  - TestDestClick
  - TestDestClick2
  - ToyFPs
  - testClickedFPS
  - test
  - GetMeToNextZonetest
  - GetCustomZone
  - GetMeToNextZoneSpecialRe
  - GetMeToNextZone
  - GetMeToNextZone2
  - CheckWheretoRun
  - GetStarterZoneFP
  - IsSameContinent
  - SwitchCont
  - ClosestFP
  - Event
    - TAXIMAP_OPENED
    - PLAYER_LEAVING_WORLD
    - PLAYER_ENTERING_WORLD

- TransportDB
  - FPs
  - FPs2
  - Ports
  - ZoneMoveOrder
  - ZoneEntry
- Locale
- Utils

### Feature
- **TBD**
- Bindings
- DB
  - Transport
  - Icon
  - Quest ?
  - Map ?

### Libs
- ACE3 (framework lib)
- HereBeDragons 2 (map lib)
- LibDataBroker-1.1 (LDB - > MVC lib) 
- LibDBIcon-1.0 (LDB minimap icon lib)

**Comment by NightofStarrs** [comment]
Lets correctly name the display windows.

'**Zone**' window/list renamed to **Quest Order List** (or similar)
'**Custom Path**' window/overlay changed to **Current Step** or something like that.

Current Step should also indicate the step number that they're on, if they are required to do anything (gossip, kill, loot, etc)
IE:

Current Step
Step 127 - Talk to _NPC_

Current Step
Step 128 - Kill 5 X
                 Kill 3 Y
                 Loot 8 Z

This way, the window is properly being used, up until we can move it into it's own custom window (Zygor or RestedEXP like eventually)
