### ISSUE TITLE
[FEATURE] - When auto selecting a quest reward - Choose the cosmetic one not learned yet (Dragonflight)

### ISSUE THREAD

**Issue by GrimNotepad** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#118]
When the reward is cosmetic, the reward picker is choosing the first one. 
Instead can we have it pick the one where the appearance is unlearned?

Since DF has so many quest rewards that are purely cosmetic the iLvl is 1 on many and it costs weird things to buy the missing cosmetics. So instead of turning off Auto Reward picker completely we could make it better :)

**Comment by Neogeekmo** [comment]
quest exemple for the dev : 
https://www.wowhead.com/quest=71085/representation-matters

**Comment by Kamian404** [comment]
WoW only displays cosmetics that are not learned yet. Already learned cosmetics wont be displayed. We could either disable auto select for cosmetics or maybe auto select the most expensive one. I'm not sure if we could grab the prices without beeing at the vendor.

Before manually buying one cosmetic from vendor
![before](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/12233929/5456f881-c395-4a98-b843-89fbcd4fb789)

After manually buying one cosmetic from vendor
![after](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/12233929/e89daed4-3482-4832-a4a9-c1dd0c393dc8)
