### ISSUE TITLE
[FEATURE] - Pause Button - Stops all APR until Unpaused

### ISSUE THREAD

**Issue by GrimNotepad** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#119]
Sometimes during the course of APR you get "distracted" by a world quest(s) or helping a guildy or you hit 70 and you want to do some gear ups but continue the APR routes later on.

It would be interesting to have a command/button/toggle that just puts a pin in the whole thing, hides the arrows the objectives and the order list to reappear when you unpause it (or on reloadui/log in) instead of disabling the addon

**Comment by Neogeekmo** [comment]
This feature will be available in V3, with the option of enableing/desabling the addon directly from the minimap icon or in settings
