### ISSUE TITLE
[ISSUE] - Error when opening map/quest log

### ISSUE THREAD

**Issue by krstcs** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#145]
### Description

I expected to not get a LUA error when opening the quest log/map.  ;)  This wasn't a direct interaction with APR.  APR was already set for Speedrun.  This is a level 61 SPriest.

### APR Version

APR 2.3.4

### APR Route

Speedrun

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [ ] Yes
- [X] No

### Lua Error

```true
12x bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))
[string "=[C]"]: in function `CreateTexture'
[string "@APR-Core/QuestTest.lua"]:877: in function `MakeMapOrderIcons'
[string "@APR-Core/QuestTest.lua"]:903: in function `MapOrderNumbers'
[string "@APR-Core/QuestTest.lua"]:925: in function <APR-Core/QuestTest.lua:920>

Locals:
(*temporary) = "bad argument #3 to '?' (Usage: local texture = self:CreateTexture([name, drawLayer, templateName, subLevel]))"
```

### Reproduction Steps

Unknown as to technical reproduction, opening the map/quest log is all I did.  Doesn't seem to pop at login.

### Last Good Version

Unknown

**Comment by Neogeekmo** [comment]
Fix in V3-Beta
