### ISSUE TITLE
[ISSUE] - "Show 10 steps on map" doesn't work

### ISSUE THREAD

**Issue by noadtome** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#152]
### Description

The "Show 10 steps on map" feature on the 3rd tab called "Arrow Options" doesn't work

### APR Version

APR 2.3.5

### APR Route

Custom Path

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

The "Show 10 steps on map" feature on the 3rd tab called "Arrow Options" doesn't work

**Comment by Neogeekmo** [comment]
Fix in V3-Beta
