### ISSUE TITLE
[ISSUE] - Progress Text in latest update gets stuck.

### ISSUE THREAD

**Issue by palanthis** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#185]
### Description

See attached. The quest progress text gets stuck, it looks like  between two steps, and will not progress. I actually had to break out an old version of APR, as this is unusable.

### APR Version

2.4.5

### APR Route

Speedrun

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

Load a character. Start questing. 

### Screenshots

![Screenshot 2023-09-17 101209](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/52150610/d0270782-1802-43cf-abd0-a7ea5c17fdd0)

**Comment by Neogeekmo** [comment]
wrong version v3-alpha-3.4 ou 3.5

**Comment by Neogeekmo** [comment]
can you send you quest order list please 
and after try to do a `/apr fr `

**Comment by NightofStarrs** [comment]
@palanthis Is this still an issue with the recent Beta version?
