### ISSUE TITLE
[ISSUE] - SoA Can't Pick Up "A Lack of Wasps" Quest

### ISSUE THREAD

**Issue by GabeClark99** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#187]
### Description

Spires of Arak step 77 has you pick up quest 37296 (A Lack of Wasps), but it is not available. 

### APR Version

APR v3 Alpha 3.10

### APR Route

Speedrun

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

1. Start the Spires of Arak guide on a character without any Spires of Arak completion
2. Progress along the guide up to step 77
3. Following the guide's instructions, attempt to pick up quest 37296 (A Lack of Wasps) from Dusk-Seer Irizzar at (43.8 48.8)

**Comment by Pahonix** [comment]
Known issue, but hasn't been fixed in the route yet. To continue, pick up and complete Befriending the Locals. Then you should be able to pick up A Lack of Wasps.

**Comment by GabeClark99** [comment]
Thank you for your quick response! Your solution worked great, and I'm back on track.
