### ISSUE TITLE
[ISSUE] - Wowup don't work anymore

### ISSUE THREAD

**Issue by Magikh42** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#195]
### Description

Despite what is said in #9, the wowup installation does not work
To make it work, just put the addon .zip file in the tagged releases

### APR Version

unrelated

### APR Route

unrelated

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

Open Wowup
Click on Get Addons
Click on Install from URL
Paste the `https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/`
Get `ERRORASSET_NOT-FOUND`

**Comment by NightofStarrs** [comment]
Hi there @Magikh42 - So, looking into this, I found an issue from WowUp's Issues, https://github.com/WowUp/WowUp/issues/1245

At this time, the requirement to add a release.json and/or folder(s) zipped as referenced is not something that we are looking into. You can still import through WowInterface using [https://www.wowinterface.com/downloads/info26457-AzerothPilotReloaded.html](https://www.wowinterface.com/downloads/info26457-AzerothPilotReloaded.html)
![image](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/40681725/85ea5b0e-fbb8-483e-b021-4ca14667de46)

We are going to look into integrating in with Wago, which apparently works with WoWUp as an alternative re-poster.

**Comment by NightofStarrs** [comment]
![image](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/40681725/3c5990be-97b6-43a3-a7b2-7ba76b3a1b7e)

We have added the current version into Wago.io for right now, while we also investigate this automatically for future addon updates.

If you find any other issues, please let us know.
