### ISSUE TITLE
[ISSUE] - V 3.0.1 overlays questlog and does not append to bottom as prior version did

### ISSUE THREAD

**Issue by Brdrker** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#204]
### Description

Both new and existing characters utilizing APR see a different quest layout with APR activated. In the prior release, APR attached itself to the bottom of the existing quest log. In the latest version released, it no longer attaches to the end of the existing question log. If I minimize the existing quest log, the frame jumps down lower on the right hand side. Pictures of non-reduced quest log with APR overlaying it, and quest log repositioning after reduced quest log.

### APR Version

v3.0.1

### APR Route

Speedrun

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [ ] Yes
- [X] No

### Reproduction Steps

Log into character
/apr
Current Step selected
Select Show Current Step Details
Select Attach to QuestLog

### Last Good Version

V3.0.0

### Screenshots

![image](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/21250895/da782520-989b-4762-b18d-e15380109dad)
![image](https://github.com/Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded/assets/21250895/9d725de2-e656-4b99-8231-f50a83b1559f)

**Comment by NightofStarrs** [comment]
Hi @Brdrker,

Thanks for letting us know this. To confirm, out of the two screenshots. The first one is what? As the second one is your 'If I minimize the existing quest log, the frame jumps down lower on the right-hand side'

Does this occur when you detach the frame and reattach it to reset the position/setting?

**Comment by Brdrker** [comment]
On 2023-11-05 14:42, J M wrote:
> Hi @Brdrker [1],
> 
> Thanks for letting us know this. To confirm, out of the two
> screenshots. The first one is what? As the second one is your 'If I
> minimize the existing quest log, the frame jumps down lower on the
> right-hand side'
> 
> Does this occur when you detach the frame and reattach it to reset the
> position/setting?

First one is displaying the APR frame laying on top of the WoW quest 
log. If you iconify the WoW Quest Log, the APR Quest indicator moves (on 
that character) to the "unlocked" location I moved that window to. If I 
expand the WoW quest log, the APR Quest Log jumps up, not affixed to the 
end of the quest log, but overlaying it.

After a bit of experimentation, I can, regretfully, get it to operate 
correctly, but if I repeatedly reduce and expand the WoW quest log 
frame, the APR Quest Log will eventually place itself, not at the base 
of the WoW Quest Frame but on top of it.

Make sense?

Brd

**Comment by Brdrker** [comment]
After messing with it a bit: 

When the WoW Quest Log is reduced (clicking icon on right side of WoW Quest Log header bar), the APR quest log goes to a what I think is its last known position. When I expand the WoW Quest Log, the APR quest log is trying to append itself to the WoW Quest Log but it appears to place itself at or around the base of the WoW Quest Log frame header, not at the end of the expanded WoW Quest Frame.

It's possible I don't fully understand what I'm attempting to do. I figured APR would move based on the WoW Quest Log frame. If I pick up a quest, the WoW Quest Log would expand downward, and the APR Quest Log would move down by that amount.

P.S. Thanks for adding the Quest IDs back in. Since I can always go look those up, while having the actual quest listed is very useful, with the IDs, if APR tells me to pick up one quest and there are multiples available, I can figure out which one I'm supposed to grab (Wowhead, etc.).

**Comment by NightofStarrs** [comment]
Ok, no worries, thanks for letting us know. This occurred somewhat at the beginning of the UI development of V3, where it was overlapping the Quest list elements on Blizzard Panel. This was fixed, but with some of the library changes that were modified today for v3.0.1 it may have broken something.

Neo will look into it tomorrow sometime.
