### ISSUE TITLE
[ISSUE] -Typos in options menu for "patch notes" for English

### ISSUE THREAD

**Issue by seadub** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#247]
### Description

In APR options for English version, I see a button and toggle for "Show path note" which is obviously meant to show patch notes.

### APR Version

3.1.8

### APR Route

n/a

### World of Warcraft Flavor

Retail (Default)

### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

- look at options
- see typo

**Comment by Neogeekmo** [comment]
will be fixed with the next release
