### ISSUE TITLE
[ISSUE] - Route stops after Jade Forest

### ISSUE THREAD

**Issue by The1stVoidRunner** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#294]
### Description

After Completing The Jade Forest in the MoP Remix Route the addon stops and doesn't start Valley of the four winds.

### World of Warcraft Flavor

Retail (Default)

### APR Status

/apr status doesent work.

### Tested with only APR

- [X] Yes
- [ ] No

### Reproduction Steps

Complete Jade Forest in MoP Remix Route.

**Comment by The1stVoidRunner** [comment]
It says that my Charactor is on step -15/246.

**Comment by The1stVoidRunner** [comment]
I was able to fix it by typing in /apr skip 16 times so unfortunately I cannot. But yes I was on V3.2.9. The Button on the UI was grayed out but force skipping using the chat command worked.

**Comment by NightofStarrs** [comment]
Ok, thank you for letting me know. In the future if you have any issues please make sure the Quest Order List is visible as something may not be properly set somewhere, or it got out of sync.

I'll go ahead and close this for now. Please feel free to use the Discord as well.
