### ISSUE TITLE
[FEATURE] - Skip Waypoints automatically

### ISSUE THREAD

**Issue by Kamian404** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#298]
### Description

Waypoints slow down the route in certain situations, for example if you can already fly or know the route by heart

### Solution

Checkbox in settings to skip waypoints automatically

### Alternative solutions

-

**Comment by Neogeekmo** [comment]
Maybe 2 checkboxes
One for auto skip waypoint (all)
And an other to auto skip waypoint only if you can fly 

And create an other ticket to add the NotSkipableWaypoint in our route for the cave waypoint
