### ISSUE TITLE
[ISSUE] - GPS Arrow gone white

### ISSUE THREAD

**Issue by Morketh** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#348]
### Description

![image](https://github.com/user-attachments/assets/559a3e49-783d-4d1e-be54-0c7b4154e036)

Arrow has gone blank i am unable to get the arrow to come back after reinstalling the addon or relaunching the game.
not really sure how to reproduce the issue as i cant get it to go back to normal for testing.

### World of Warcraft Flavor

Retail (Default)

### APR Status

{{"Class","MAGE"},{"Continent","The Shadowlands"},{"Time & Date","Fri Sep 27 18:22:59 2024"},{"Language","enUS"},{"Name","Garagegnome"},{"Realm","Draenor"},{"World Coordinates","-4954.30, -2946.10"},{"Level","70"},{"AddOn Version","v4.5.0"},{"Faction","Alliance"},{"Coordinates","52.99, 46.87"},{"Client Build","56647"},{"Client Version","11.0.2"},{"Index, Step","424, Qpart"},{"Route","1670-Shadowlands-StoryOnly-A"},{"Zone","Bastion"}}

### Tested with only APR

- [X] Yes
- [ ] No

### Lua Error

N/A

### Reproduction Steps

1. open game
2. arrow is gone
3. Arrow appears in stormwind and is now back
4. teleported back to Oribos and arrow is working again.....?

**Comment by NightofStarrs** [comment]
Troubleshooted over Discord. User was in the wrong zone, and when they ported to another zone it flashed and when they went to the right zone it showed properly while also doing an `/apr forcereset`

Since the issue was resolved, I'll go ahead and close, as something was causing the arrow to populate when it shouldn't have since you were not in the right zone.

**Comment by Morketh** [comment]
> Troubleshooted over Discord. User was in the wrong zone, and when they ported to another zone it flashed and when they went to the right zone it showed properly while also doing an `/apr forcereset`
> 
> Since the issue was resolved, I'll go ahead and close, as something was causing the arrow to populate when it shouldn't have since you were not in the right zone.

For clarification sake...
I did not use the slash command. Only TP to stormwind city
