### ISSUE TITLE
The green dotted line on the minimap doesn't point in the right direction when using a minimap that rotates

### ISSUE THREAD

**Issue by jonjbm** [Azeroth-Pilot-Reloaded/azeroth-pilot-reloaded#7]
I use a minimap addon called SexyMap which has an option called "Rotate Minimap", which makes the minimap rotate and makes your character's arrow on it always face directly up. With this option selected the green dotted line on the minimap from APR points as if the minimap isn't rotating (aka, usually the wrong way). This was not the case in 9.2.7 with AAP.

Thank you very much for carrying AAP forward, btw! :)

**Comment by Rycia** [comment]
Though AAP worked with that in 9.2.7, does it work now in the DF prepatch? I'd try that out, because it's probably a AAP issue that was carried into APR. Let me know how it goes!
